# Generated by Django 4.2.1 on 2023-05-10 14:23

from django.db import migrations, models
import django.db.models.deletion


def create_initial_data(apps, schema_editor):
    Groups = apps.get_model('tasks_students_bank', 'Groups')

    # Создание предметов
    subjects_data = [
        {'group_name': 'А-1'},
        {'group_name': 'Б-1'},
        {'group_name': 'В-1'},
    ]
    for data in subjects_data:
        Groups.objects.create(**data)


class Migration(migrations.Migration):
    dependencies = [
        ('tasks_students_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='group_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='tasks_students_bank.groups'),
        ),
        migrations.RunPython(create_initial_data),
    ]
