# Generated by Django 4.2.1 on 2023-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_students_bank', '0002_alter_banktasks_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktasks',
            name='subject',
            field=models.CharField(choices=[('math', 'Математика'), ('rus', 'Русский язык'), ('inform', 'Информатика')], max_length=255),
        ),
    ]
